---
- name: Configuration du serveur EC2
  hosts: all
  become: true
  tasks:
    - name: Mise Ã  jour des paquets
      apt:
        update_cache: yes

    - name: Installation de Docker
      apt:
        name: docker.io
        state: present

    - name: Lancement du service Docker
      service:
        name: docker
        state: started
        enabled: yes
